services:

  adguard:
    container_name: adguardhome

    image: lkpot/adguardhome

    network_mode: host

    cap_drop:
      - All

    cap_add:
      - CAP_NET_BIND_SERVICE

    volumes:
      - ./etc-adguardhome:/etc/adguardhome

    restart: unless-stopped
