services:
  adguard:
    container_name: adguardhome

    image: lkpot/adguardhome

    network_mode: host

    cap_drop:
      - All

    cap_add:
      - CAP_NET_BIND_SERVICE

    expose:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp

    user: ${UID}:${GID}

    volumes:
      - ./etc-adguardhome:/etc/adguardhome

    restart: unless-stopped
